### ISSUE TITLE
Migrate library to KiCad v6

### ISSUE THREAD

**Issue by Techmo2** [lucanastasio/PCIexpress-KiCad#2]
At the moment, attempting to use the library with KiCad results in the following:
`can't open file C:\Program Files\KiCad\6.0\share\kicad\template\<any pcie template here>\meta\info.html (error 3: The system cannot find the path specified.)`
I installed the template into the program directory for convenience's sake, but attempting to use the template via user templates results in the same issue.
I suspect the template format may have changed slightly with the new version.

**Comment by lucanastasio** [comment]
Thanks for reporting the issue, I will investigate as soon as I can.

**Comment by Velho** [comment]
I had the same issue with 5.1 as well

**Comment by lucanastasio** [comment]
Actually, this project is not a KiCad template, I have to make some adjustments (pull requests are welcome) to make it a template. It is however a template repository on GitHub, which is different. You can still download or clone it and use it like a regular KiCad project.

**Comment by Velho** [comment]
@lucanastasio The idea is to open it as a project?

**Comment by lucanastasio** [comment]
Yes, there are separate projects for the different card sizes, I would like to convert it to the corresponding templates as suggested in this issue.
